name: OWASP ZAP Baseline Scan

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  zap-baseline-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.15.0
        with:
          target: "https://github.com/youneschami/github-actions-demo-project.git"
          fail_action: false
          issue_title: ""
          cmd_options: "-a"  # active/passive options
      - name: Upload ZAP JSON
        uses: actions/upload-artifact@v4
        with:
          name: zap-json
          path: zap/results.json

